version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - 5000:5000
    env_file:
      - backend/.env
    depends_on:
      - database

  client:
    build:
      context: ./client
    ports:
      - 80:80
    depends_on:
      - backend

  database:
    image: mongo
    ports:
      - 27017:27017
